# Generated by Django 5.0.6 on 2024-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
